### ISSUE TITLE
Error while generating frames: program not found

### ISSUE THREAD

**Issue by EveryoneHatesRay** [redpenguinyt/console-video-player#1]
Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target\debug\gemini-video-player.exe video.mov`
Error while generating frames: program not found
error: process didn't exit successfully: `target\debug\gemini-video-player.exe video.mov` (exit code: 1)

**Comment by EveryoneHatesRay** [comment]
What do I do?

**Comment by redpenguinyt** [comment]
do you have ffmpeg installed?

**Comment by redpenguinyt** [comment]
closing stale issue
